# Generated by Django 5.2.12 on 2026-03-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendu',
            new_name='sells',
        ),
    ]
