# Generated by Django 5.2.12 on 2026-03-09 23:17

import public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sku',
            field=models.CharField(default=public.models.generate_order_number, max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
