# Generated by Django 5.2.12 on 2026-03-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_order_sku_alter_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
